2025-01-12 23:01:40,690 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:01:40,702 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:01:40,704 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:01:40,705 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:01:40,727 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:01:40,738 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:01:40,744 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:01:40,753 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:01:40,914 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:01:49,574 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:01:49,580 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:01:49,583 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:01:49,590 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:01:49,603 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:01:49,623 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:01:49,632 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:01:49,654 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:01:49,839 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:02:49,986 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:02:50,011 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:02:50,025 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:02:50,033 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:02:50,063 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:02:50,064 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:02:50,072 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:02:50,103 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:02:50,472 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:03:42,691 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:03:42,692 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:03:42,706 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:03:42,711 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:03:42,714 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:03:42,717 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:03:42,737 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:03:42,800 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:03:42,989 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:04:42,097 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:04:42,102 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:04:42,103 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:04:42,103 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:04:42,122 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:04:42,149 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:04:42,167 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:04:42,180 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:04:42,451 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:06:04,052 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:06:04,065 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:06:04,072 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:06:04,076 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:06:04,091 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:06:04,113 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:06:04,116 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:06:04,136 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:06:04,355 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:06:50,189 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:06:50,201 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:06:50,202 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:06:50,206 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:06:50,218 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:06:50,243 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:06:50,255 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:06:50,257 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:06:50,585 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:08:36,619 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:08:36,633 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:08:36,635 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:08:36,648 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:08:36,652 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:08:36,686 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:08:36,695 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:08:36,705 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:08:36,983 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:11:22,624 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:11:22,629 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:11:22,637 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:11:22,642 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:11:22,645 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:11:22,677 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:11:22,679 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:11:22,693 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:11:22,838 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-12 23:11:37,152 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: saibunny/fil-shortstory-svm-thesis: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 10, 12, '            except Exception as e:\n')))
2025-01-12 23:11:37,165 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', TokenError('EOF in multi-line string', (291, 8)))
2025-01-12 23:11:37,168 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: mattboehm/otree-core: ('An exception occurred ', TokenError('EOF in multi-line string', (160, 0)))
2025-01-12 23:11:37,171 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-12 23:11:37,180 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-12 23:11:37,236 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: erny/SudsSigner: ('An exception occurred ', TokenError('EOF in multi-line statement', (10, 0)))
2025-01-12 23:11:37,241 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: Rits1272/Conduit: ('An exception occurred ', TokenError('EOF in multi-line statement', (197, 0)))
2025-01-12 23:11:37,242 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-12 23:11:37,411 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    """\n')))
2025-01-13 10:01:21,445 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', TokenError('EOF in multi-line statement', (34, 0)))
2025-01-13 10:01:21,450 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 236, 8, '        return self._send_request_with_retry(\n')))
2025-01-13 10:01:21,456 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: chen3652/ENGR133FallProject2020: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 150, 4, '    plt.imshow(imageToReturn, cmap=plt.get_cmap("gray"), vmin=0, vmax=1)\n')))
2025-01-13 10:01:21,468 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-13 10:01:21,474 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: VOLTTRON/volttron-energyplus: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 301, 8, '        return None\n')))
2025-01-13 10:01:21,496 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-13 10:01:21,503 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: tle-huu/xbrain-hackathon: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 92, 4, '    return newsitems\n')))
2025-01-13 10:01:21,509 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: fdsAlertLogic/pgsanity: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 35, 4, '    return msglist\n')))
2025-01-13 10:01:21,690 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: Nimitkothari/Automatic-Pickle: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 115, 4, '    except Exception as e:\n')))
2025-01-13 10:11:46,486 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 236, 8, '        return self._send_request_with_retry(\n')))
2025-01-13 10:11:46,487 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-13 10:11:46,496 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: chen3652/ENGR133FallProject2020: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 150, 4, '    plt.imshow(imageToReturn, cmap=plt.get_cmap("gray"), vmin=0, vmax=1)\n')))
2025-01-13 10:11:46,508 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-13 10:11:46,519 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: VOLTTRON/volttron-energyplus: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 301, 8, '        return None\n')))
2025-01-13 10:11:46,555 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: fdsAlertLogic/pgsanity: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 35, 4, '    return msglist\n')))
2025-01-13 10:11:46,561 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-13 10:11:46,566 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: tle-huu/xbrain-hackathon: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 92, 4, '    return newsitems\n')))
2025-01-13 10:11:46,790 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    ""\'\n')))
2025-01-13 10:17:27,926 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: carcasslizard/Stef-Of-The-Winds: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 106, 16, '                else:\n')))
2025-01-13 10:17:27,928 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: arzhuch/python-advanced: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 43, 4, '    def check_load(self):\n')))
2025-01-13 10:17:27,933 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: erikselin/snowflake-connector-python: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 236, 8, '        return self._send_request_with_retry(\n')))
2025-01-13 10:17:27,938 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: chen3652/ENGR133FallProject2020: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 150, 4, '    plt.imshow(imageToReturn, cmap=plt.get_cmap("gray"), vmin=0, vmax=1)\n')))
2025-01-13 10:17:27,964 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: VOLTTRON/volttron-energyplus: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 299, 8, '        return None\n')))
2025-01-13 10:17:27,993 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: fdsAlertLogic/pgsanity: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 35, 4, '    return msglist\n')))
2025-01-13 10:17:28,013 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: tle-huu/xbrain-hackathon: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 92, 4, '    return newsitems\n')))
2025-01-13 10:17:28,033 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: pbs-lzy/Travelling-Route-Generation-System: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 87, 8, '        location = {\n')))
2025-01-13 10:17:28,170 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    ""\'\n')))
2025-01-13 10:19:03,130 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: satskyi1991/itea_feb_proj: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 18, 8, '        "title": f"Category{unique_arg}",\n')))
2025-01-13 10:19:03,199 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    ""\'\n')))
2025-01-13 10:19:03,287 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: Griffbone/RocketBuilder: ('An exception occurred ', TokenError('EOF in multi-line string', (40, 4)))
2025-01-13 10:19:03,502 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: Rith-GitHub/FoodJI: ('An exception occurred ', TokenError('EOF in multi-line string', (574, 145)))
2025-01-13 10:19:03,747 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: aishwaryjoshi94/mongo-connector: ('An exception occurred ', TokenError('EOF in multi-line string', (501, 8)))
2025-01-13 10:19:03,951 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: godjuansan/K-Puzzle: ('An exception occurred ', TokenError('EOF in multi-line string', (387, 0)))
2025-01-13 10:19:04,453 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: PeteGentile/PyPulse: ('An exception occurred ', TokenError('EOF in multi-line string', (1073, 35)))
2025-01-13 10:19:04,504 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: vyam/ddlparse: ('An exception occurred ', TokenError('EOF in multi-line string', (647, 8)))
2025-01-13 10:19:07,065 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: Kendallhabra/ME507-LIDAR-Car: ('An exception occurred ', TokenError('EOF in multi-line string', (338, 20)))
2025-01-13 10:49:58,244 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_0.jsonl  repo_name: satskyi1991/itea_feb_proj: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 18, 8, '        "title": f"Category{unique_arg}",\n')))
2025-01-13 10:49:58,410 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_7.jsonl  repo_name: toto6321/SpMv: ('An exception occurred ', IndentationError('unindent does not match any outer indentation level', ('<tokenize>', 67, 4, '    ""\'\n')))
2025-01-13 10:49:58,514 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_6.jsonl  repo_name: Griffbone/RocketBuilder: ('An exception occurred ', TokenError('EOF in multi-line string', (40, 4)))
2025-01-13 10:49:58,751 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_2.jsonl  repo_name: Rith-GitHub/FoodJI: ('An exception occurred ', TokenError('EOF in multi-line string', (574, 145)))
2025-01-13 10:49:58,972 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_5.jsonl  repo_name: aishwaryjoshi94/mongo-connector: ('An exception occurred ', TokenError('EOF in multi-line string', (501, 8)))
2025-01-13 10:49:59,158 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_1.jsonl  repo_name: godjuansan/K-Puzzle: ('An exception occurred ', TokenError('EOF in multi-line string', (387, 0)))
2025-01-13 10:49:59,620 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_4.jsonl  repo_name: PeteGentile/PyPulse: ('An exception occurred ', TokenError('EOF in multi-line string', (1073, 35)))
2025-01-13 10:49:59,817 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_8.jsonl  repo_name: vyam/ddlparse: ('An exception occurred ', TokenError('EOF in multi-line string', (647, 8)))
2025-01-13 10:50:02,258 - ERROR: Error while reindenting file ./new-python-dataset/cleaned_data/data_3.jsonl  repo_name: Kendallhabra/ME507-LIDAR-Car: ('An exception occurred ', TokenError('EOF in multi-line string', (338, 20)))
